config/routes.rb
Rails.application.routes.draw do
  resources :products

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params[:product]
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Derteleshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="header">
    <a href="/"><h1>Derteleshop</h1></a>
</div>

<div class="menu visible" ng-click="toggleOverlay($event)">
    <div class="burger-menu">
      <div class="burger-menu-line burger-menu-line--top"></div>
      <div class="burger-menu-line burger-menu-line--mid"></div>
      <div class="burger-menu-line"></div>
      <div class="inside-menu">
        <h6 class="inside-menu-title">MENU</h6>
      </div>
    </div>
  </div>

<div id="container" class="cols">
    <div class="box one">
        <img src="https://ifub1.s3.amazonaws.com/uploads/square/avatar/59/Laken-Paradis_start2.jpg" width="200px">
    </div>
    <div class="box two">
        <img src="https://ifub1.s3.amazonaws.com/uploads/square/avatar/91/Obstgeweih_start.jpg" width="300px">
    </div>
    <div class="box three"></div>
    <div class="box four"></div>
    <div class="box five"></div>
    <div class="box six"></div>
    <div class="box five"></div>
    <div class="box six"></div>
    <div class="box one"></div>
    <div class="box three"></div>
    <div class="box two"></div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<a href="/products">
  <div class="stage">
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
    <div class="layer"></div>
  </div>
  <div class="stage__1">
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
    <div class="slayer"></div>
  </div>
  <div class="stage__2">
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
    <div class="dlayer"></div>
  </div>


</a>